---
title: "R Notebook"
output: html_notebook
---

```{r}
# load libraries
#install.packages("manifestoR")
library(manifestoR)
library(dplyr)
library(stringr)
library(purrr)
library(tibble)
```

```{r}
# set api key - reminder to self to later add this file to the gitignore before pushing
mp_setapikey("manifesto_apikey.txt")
```

```{r}
# get the dataset
mpds <- mp_maindataset()
# look at names
names(mpds)
```
```{r}
# check to see what the dataset looks like
mpds
```
```{r}
mp_availability(TRUE)
```

Get the entire corpus
```{r}
all <- mp_availability(TRUE)
all_docs <- mp_corpus(all)
```

```{r}
english_only <- mp_availability(TRUE) %>% 
 filter(language == "english")

english_docs <- mp_corpus(english_only)
length(english_docs)

```

```{r}
class(all_docs)
typeof(all_docs)
length(all_docs)
```

```{r}
all_docs[[1]]
content(all_docs[[1]])
```
```{r}
all_texts <- sapply(all_docs, content)
```


```{r}
# count word count in all documents
doc_word_counts <- str_count(all_texts, boundary("word"))
# mean word count in all 
mean(doc_word_counts)
# median word count in all
median(doc_word_counts)
# word count in the longest document
max(doc_word_counts)
# min word count
min(doc_word_counts)
```

```{r}
# how many unique countries? 67 countries
mpds %>%
  select(countryname) %>%
  unique() %>%
  nrow()
```

```{r}
mpds %>%
  select(parfam) %>%
  unique() %>%
  nrow()
```

```{r}
mpds %>%
  group_by(parfam) %>%
  summarize(count=n()) %>% 
  arrange(desc(count))
```


```{r}
total_n <- nrow(mpds)

mpds %>% 
  group_by(countryname) %>% 
  summarize(
    count = n(),
    pct_of_total = 100 * (count / total_n)
  ) %>% 
  arrange(desc(count))

```

```{r}
summary(mpds$edate)
```

```{r}
mpds %>% 
  arrange((edate))

mpds %>% 
  arrange(desc(edate))
```
```{r}
all_docs_df <- keep(as.list(all_docs), ~ !is.null(.x$content)) |>
  map_dfr(~ {
    txt <- .x$content$text
    tibble(
      text         = if (is.null(txt) || length(txt) == 0) NA_character_ 
                     else paste(txt, collapse = " "),
      party        = as.character(.x$meta$party),
      date         = as.character(.x$meta$date),
      manifesto_id = as.character(.x$meta$manifesto_id),
      language     = as.character(.x$meta$language)
    )
  })

nrow(all_docs_df)

write.csv(all_docs_df, "manifesto_texts.csv",
          row.names = FALSE, fileEncoding = "UTF-8")


```

```{r}
mpds %>%
  select(party, parfam, partyname) %>%
  distinct() %>% 
  write.csv("party_families.csv", row.names = FALSE)
```

